
auth.token=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

defaults.org=swtlabs-vn
defaults.project=rehand-app

defaults.url=https://sentry.io/
