#!/usr/bin/env python3
"""
Core ML Model Training Script for neck_stretch
Auto-generated by train_models.ts
"""

import coremltools as ct
import numpy as np
import json
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras

def load_training_data(exercise_type):
    """Load preprocessed training data"""
    with open(f'training_data/{exercise_type}_train.json', 'r') as f:
        train_data = json.load(f)
    
    with open(f'training_data/{exercise_type}_valid.json', 'r') as f:
        valid_data = json.load(f)
    
    return train_data, valid_data

def preprocess_features(data):
    """Convert feature sequences to model input format"""
    X = []
    y = []
    
    for sample in data:
        features = sample['features']
        ground_truth = sample['groundTruth']
        
        # Flatten sequence data
        angles = np.array(features['angleSequence']).flatten()
        velocities = np.array(features['velocitySequence']).flatten()
        roms = np.array(features['romSequence']).flatten()
        
        # Combine features
        feature_vector = np.concatenate([angles, velocities, roms])
        X.append(feature_vector)
        
        # Create target vector
        phase_encoding = {
            'eccentric': [1, 0, 0, 0],
            'concentric': [0, 1, 0, 0], 
            'isometric': [0, 0, 1, 0],
            'transition': [0, 0, 0, 1]
        }
        
        target = []
        target.extend(phase_encoding[ground_truth['phase']])
        target.append(1 if ground_truth['isRepEnd'] else 0)
        target.append(ground_truth['qualityScore'] / 100.0)
        
        y.append(target)
    
    return np.array(X), np.array(y)

def build_tcn_model(input_shape, output_shape):
    """Build Temporal Convolutional Network"""
    model = keras.Sequential([
        keras.layers.Dense(128, activation='relu', input_shape=input_shape),
        keras.layers.Dropout(0.3),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(32, activation='relu'),
        keras.layers.Dense(output_shape, activation='sigmoid')
    ])
    
    model.compile(
        optimizer='adam',
        loss='mse',
        metrics=['accuracy']
    )
    
    return model

def main():
    exercise_type = 'neck_stretch'
    print(f"Training model for {exercise_type}")
    
    # Load data
    train_data, valid_data = load_training_data(exercise_type)
    
    # Preprocess
    X_train, y_train = preprocess_features(train_data)
    X_valid, y_valid = preprocess_features(valid_data)
    
    # Scale features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_valid_scaled = scaler.transform(X_valid)
    
    print(f"Training data shape: {X_train_scaled.shape}")
    print(f"Target data shape: {y_train.shape}")
    
    # Build model
    model = build_tcn_model((X_train_scaled.shape[1],), y_train.shape[1])
    
    # Train model
    history = model.fit(
        X_train_scaled, y_train,
        validation_data=(X_valid_scaled, y_valid),
        epochs=50,
        batch_size=32,
        verbose=1
    )
    
    # Convert to Core ML
    coreml_model = ct.convert(
        model,
        inputs=[ct.TensorType(shape=X_train_scaled.shape[1:])],
        outputs=[ct.TensorType(shape=y_train.shape[1:])],
        convert_to="mlprogram"
    )
    
    # Save model
    output_path = f"../models/{exercise_type}.mlpackage"
    coreml_model.save(output_path)
    print(f"Model saved to {output_path}")

if __name__ == "__main__":
    main()
